#!/bin/bash

# Legg ett sted som er i $PATH
# F.eks. lag en mappe ~/bin/ som du legger i $PATH (se .bashrc)

# Bruk:
# jcr Foobar.java argument1 argument2...

set -e

echo "javac $1"
javac $1
echo "java $(basename ${1%.*} ${@:2})"
java $(basename ${1%.*}) "${@:2}"